server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-matricula-service
          uri: lb://ms-matricula-service
          predicates:
            - Path=/matricula/**, /expediente/**, /estudiante/**, /curso/**
        - id: ms-capacitacion-service
          uri: lb://ms-capacitacion-service
          predicates:
            - Path=/capcurso/**, /certificado/**, /participante/**
        - id: ms-reporte-service
          uri: lb://ms-reporte-service
          predicates:
            - Path=/destinatario/**, /mensaje/**, /notificacion/**


